remote_theme: pages-themes/time-machine@v0.2.0
title: [Deb Install]
description: [Debian based apps Installation Automation]
show_downloads: [false]
# google_analytics: [Your Google Analytics tracking ID]
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
